[package]
name = "octopush_infra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
octopush_core = { path = "../octopush_core" }

eyre = { workspace = true }
tracing = { workspace = true }
