[package]
name = "gitea_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitea_raw_client = { path = "../gitea_raw_client" }

async-trait = { workspace = true }

reqwest = "0.11.15"
