[package]
name = "octopush_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitea_client = { path = "../gitea_client" }

async-trait = { workspace = true }
eyre = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

rand = "0.8.5"
hex = "0.4.3"
git2 = { version = "0.18.3", features = [
  "vendored-libgit2",
  "vendored-openssl",
] }
serde = { version = "1.0.199", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
octocrab = { version = "0.38.0", features = ["futures-core", "futures-util"] }
